version: '3'

services:
  node:
    build: ./docker/node
    volumes:
      - ./node:/node
    tty: true

  https-portal3000:
    image: steveltn/https-portal:1
    ports:
      - '3443:443'
    environment:
      STAGE: local
      DOMAINS: 'localhost -> http://host.docker.internal:3000'